### ISSUE TITLE
1612418 - Phạm Lưu Trọng Nghĩa

### ISSUE THREAD

**Issue by nghiaplt** [dpnam/DS-Final-Project#1]
Chào 2 bạn, mình là Nghĩa, mình xin được review về project của 2 bạn như sau:

- Về ý tưởng: Ý tưởng của đề tài gần gũi với thực tế, nhưng về mặt đưa ứng dụng vào thực tế thì sẽ gặp một cản trở như: Tại sao người dùng phải sử dụng app của mình để dự đoán giá nhà trong khi họ có thể tự filter danh sách các căn hộ và tự dự đoán giá? (Thực ra nhóm mình cũng đang bị dính vấn đề này).

- Về kĩ thuật: Các bạn có comment, chia code thành từng function, từng block, clear code, dễ đọc, nhóm mình học hỏi được khá nhiều về mặt này.

- Mình có 2 câu hỏi:
  + Nếu feed data vào model, thì thật sự những cột nào sẽ được sử dụng? Vì hiện tại mình thấy có những cột như: date_sold, mortgage nếu feed vào model sẽ không có ý nghĩa nhiều cho output là dự đoán giá nhà.
  + Các bạn sẽ sử dụng phương pháp nào để normalize data của những cột như thế nào để feed vào model? Vì ở đây mình thấy có cột value là text, value là ID (address_code), value là số thập phân (taxes).

Cám ơn các bạn.

**Comment by dpnam** [comment]
Chào Nghĩa, mình là Nam, mình xin trả lời các thắc mắc của bạn như sau:
- Về ý tưởng: Nhóm mình muốn thiết kế cho người dùng (cả người bán và người mua) có thể có một cái giá tham khảo (giá này được tạo ra từ mô hình máy học fit cho **dữ liệu bán các căn hộ thành công** trong năm 2019) về căn hộ đang được xem xét. Đối với những người muốn bán nhà (đặc biệt là những người chưa có kinh nghiệm) thì họ không cần phải tốt chi phí để nhờ người làm trong lĩnh vực bất động sản tư vấn giúp chọn một cái giá để bán, thay vào đó họ có thể sử dụng app của bọn mình để đưa ra một giá hợp lý (phù hợp với tình hình thực tế). Còn phía người mua, do tin rao bán nhà là ai muốn đăng giá bao nhiêu thì đăng, nên rất khó kiểm soát về sự chính xác, nên người mua có thể dùng app của bọn mình để xem là giá đó có hợp lý với thị trường hay không.
- Trả lời các câu hỏi:
    + Đúng như bạn nói, do đây chỉ mới là bước đưa ra câu hỏi và thu thập thông tin nên nhóm mình muốn show ra hết tất cả các cột lấy được để xem tổng quan dữ liệu, về sau nhóm mình sẽ có bước tiền xử lý dữ liệu để chọn ra các cột có ý nghĩa cho việc dự đoán output.
    + Hiện tại, normalize thì nhóm mình chưa chọn luôn do đợi bọn mình lựa ra các cột có ý nghĩa với xử lý dữ liệu thiếu nữa :). 

Cám ơn bạn đã review về project của nhóm mình.
Chúc nhóm bạn làm tốt đề tài :3.
