### ISSUE TITLE
1612377 - Tô Hiếu Minh

### ISSUE THREAD

**Issue by tsminh** [dpnam/DS-Final-Project#2]
Chào các bạn, phần review thì Nghĩa đã nói khá giống mình về mặt ý tưởng và kỹ thuật. 
Mình chỉ có câu hỏi là mình thấy phần địa chỉ các ban có bao gồm cả số nhà, số unit (chung cư), các ban có nghĩ phần địa chỉ cụ thể như vậ có giúp ích gì cho việc training không ? tại mình nghĩ chỉ cần tên đường là đủ.
Cám ơn các ban :D

**Comment by dpnam** [comment]
Chào Minh, mình là Nam, mình xin phản hồi review của bạn: Đúng là phần địa chỉ của mỗi căn hộ là khác nhau (16011 căn hộ thì có đúng 16011 địa chỉ khác nhau) nên cần phải xử lý một chút và nhóm mình đang tìm cách tách **tên đường** từ địa chỉ để xem có thuận lợi gì cho việc training không?.

Cám ơn bạn đã review :D 
Chúc bạn làm tốt đề tài :3.
