### ISSUE TITLE
1612418 - Phạm Lưu Trọng Nghĩa

### ISSUE THREAD

**Issue by nghiaplt** [dpnam/DS-Final-Project#3]
Chào nhóm, mình thấy nhóm bạn bỏ rất nhiều tâm huyết vào đồ án lần này, well done!. Mình học được từ nhóm những điều sau:

- Nhóm chọn các cột data rất kĩ để train. Thấy được cột mortage (giá thuê) gây ảnh hưởng nhiều đến việc predict giá bán là một việc khá hay. Vì theo mình biết ở các bang khác nhau, tỉ lệ mortage/price sẽ khác nhau, nên nếu bạn có định mở rộng data ra các bang khác, cột mortage lúc này sẽ phát huy tác dụng.
- Nhóm bạn phân chia cột, rút trích các feature khá hợp lý, mình tâm đắc ở phần convert từ 12 month --> 4 season.
- Nhóm phân tích khá kĩ về underfitting và overfitting cho từng tham số với từng classifier.
- Slide của nhóm trình bày rõ ràng cụ thể và chi tiết.

Và mình cũng có vài góp ý sau:

- Vì slide cụ thể và chi tiết, nên cá nhân mình thấy có vài slide nhóm để nhiều chữ trong đó, đôi khi sẽ gây rối mắt. Nhóm có thể để phần phân tích, trình bày underfit và overfit qua notebook.
- Nếu để mô hình có thể hoạt động ở thực tế. Mình nghĩ nhóm nên thêm thông tin là thời gian chạy của thuật toán. (Ex: Decision Tree Regressor có thời gian chạy trung bình trên một dòng dữ liệu là mất bao nhiêu thời gian?).
- Một góc thú vị: Nhóm có thể vẽ một biểu đồ dự đoán giá tương lai của một nơi ở (Ex: Chỉ cần address_locality, các thông tin ở region) theo thời gian được không ? (Lúc này sẽ thiếu nhiều thông tin như #BedRoom, #BathRoom, ...).

**Comment by nghialm269** [comment]
> Vì slide cụ thể và chi tiết, nên cá nhân mình thấy có vài slide nhóm để nhiều chữ trong đó, đôi khi sẽ gây rối mắt. Nhóm có thể để phần phân tích, trình bày underfit và overfit qua notebook.

Do không soạn phần tài liệu báo cáo và slide là phiên bản ngắn cho file notebook, với nội dung của đồ án có yêu cầu phân tích underfitting và overfitting, nên nhóm mình muốn thêm vào slide để thầy đọc nhanh qua, và phần phân tích nhóm mình cũng cố gắng làm ngắn gọn nhất và đầy đủ ý, đồng thời nhóm cũng muốn show hết tất cả kỹ thuật mà nhóm đã làm để giúp người xem hiểu rõ hơn.

> Nếu để mô hình có thể hoạt động ở thực tế. Mình nghĩ nhóm nên thêm thông tin là thời gian chạy của thuật toán. (Ex: Decision Tree Regressor có thời gian chạy trung bình trên một dòng dữ liệu là mất bao nhiêu thời gian?).

Thời gian chạy thì mình nghĩ là một phần phụ thuộc vào cấu hình của máy dùng để chạy nữa, và trong đồ án này, nhóm mình chỉ cố gắng tuân thủ quy trình của Data Science nên nhóm mình không phân tích kỹ phần thời gian chạy của các mô hình máy học, nhưng nhóm cảm ơn góp ý này của bạn.

> Một góc thú vị: Nhóm có thể vẽ một biểu đồ dự đoán giá tương lai của một nơi ở (Ex: Chỉ cần address_locality, các thông tin ở region) theo thời gian được không ? (Lúc này sẽ thiếu nhiều thông tin như #BedRoom, #BathRoom, ...).

Ý tưởng này của bạn mình thấy rất hay, nhóm mình không chắc là có làm được không nhưng về sau sẽ cố gắng thử xem sao.

Dù gì nhóm cũng đã nộp bài, nên dự định về sau khi rảnh sẽ thử 2 phần góp ý về thời gian chạy và vẽ biểu đồ giá theo khu vực để đồ án được hoàn thiện hơn.

Cảm ơn những góp ý của nhóm bạn, chúc nhóm bạn năm mới vui vẻ.
