### ISSUE TITLE
1612377 - Tô Hiếu Minh

### ISSUE THREAD

**Issue by tsminh** [dpnam/DS-Final-Project#4]
Chào các bạn, mình rất ấn tượng với kết quả của các bạn. Accuracy rất cao. Bên cạnh đó mình có thêm một số góp ý:
- file notebook chắc mấy bạn quên run all nên một số block hông thấy kết quả chạy.
- các bạn có thể bổ sung các biểu đồ vào để sinh động và dễ hình dung hơn về dữ liệu của các bạn.

Chúc các bạn năm mới vui vẻ.

**Comment by nghialm269** [comment]
Chào bạn, cảm ơn bạn đã góp ý cho nhóm.

> file notebook chắc mấy bạn quên run all nên một số block hông thấy kết quả chạy.

Do phần output quá nhiều nên nhóm mình đã clear hết, chỉ giữ lại phần `Thiết kế pipeline tiền xử lý dữ liệu` trở xuống.

Nếu bạn vẫn muốn xem lại output của các cell trước đó, có thể xem trong git log của repo này, ví dụ ở đây có output của phần [tách dữ liệu và quan sát dữ liệu](https://github.com/dpnam/DS-Final-Project/blob/d69778d4802552437622b9e3fd363ef5bca77c10/real-estate-California/HousePrice_California.ipynb) và ở đây có output của [phần thu thập dữ liệu](https://github.com/dpnam/DS-Final-Project/blob/8686ac29f7696373ad724ea9ca3e19b3cf438e3e/real-estate-California/HousePrice_California.ipynb).

> các bạn có thể bổ sung các biểu đồ vào để sinh động và dễ hình dung hơn về dữ liệu của các bạn.

Về phần này thì nhóm mình có làm một phần quan sát từng cột dữ liệu để đưa ra cách thức tiền xử lý dữ liệu, về output của phần đó thì có ở link phía trên, bạn có thể xem qua.

Chúc nhóm bạn năm mới vui vẻ.
